-- Table: public."AnimalType"
-- DROP TABLE public."AnimalType";

CREATE TABLE public."AnimalType"
(
    "Id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    "Code" character varying(16) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_AnimalType" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."AnimalType"
    OWNER to zoo_manager;

COMMENT ON COLUMN public."AnimalType"."Id"
    IS 'Primary key animal type table';

COMMENT ON COLUMN public."AnimalType"."Code"
    IS 'Code for the animal register.';

COMMENT ON COLUMN public."AnimalType"."Name"
    IS 'Code for the animal register.';


-- Table: public."Animal"
-- DROP TABLE public."Animal";

CREATE TABLE public."Animal"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Id_AnimalType" smallint NOT NULL,
    "Code" character varying(16) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "DateAdmission" timestamp without time zone NOT NULL,
    "Weight" numeric(8,2) NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "DateUpdated" timestamp without time zone,
    "UserCreated" uuid NOT NULL,
    "UserUpdated" uuid,
    "IdSuscripcion" smallint,
    CONSTRAINT "PK_Animal" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ANIMAL_ANIMAL_TYPE" FOREIGN KEY ("Id_AnimalType")
        REFERENCES public."AnimalType" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE public."Animal"
    OWNER to zoo_manager;
COMMENT ON TABLE public."Animal"
    IS 'Store data information about animals';

COMMENT ON COLUMN public."Animal"."Id"
    IS 'Primary key animal table';

COMMENT ON COLUMN public."Animal"."Id_AnimalType"
    IS 'Foreign Key for table animal type.';

COMMENT ON COLUMN public."Animal"."Code"
    IS 'Code for the animal register.';

COMMENT ON COLUMN public."Animal"."Name"
    IS 'Code for the animal register.';

COMMENT ON COLUMN public."Animal"."DateAdmission"
    IS 'Date for the register was entered the zoo.';

COMMENT ON COLUMN public."Animal"."Weight"
    IS 'Weight for the animal register.';

COMMENT ON COLUMN public."Animal"."DateCreated"
    IS 'Date for the register was created in database.';

COMMENT ON COLUMN public."Animal"."DateUpdated"
    IS 'Date for the register was updated in database.';

COMMENT ON COLUMN public."Animal"."UserCreated"
    IS 'User that to register in database.';

COMMENT ON COLUMN public."Animal"."UserUpdated"
    IS 'User that to update in database.';

-- Index: ANIMAL_ANIMAL_TYPE_FK
-- DROP INDEX public."ANIMAL_ANIMAL_TYPE_FK";

CREATE INDEX "ANIMAL_ANIMAL_TYPE_FK"
    ON public."Animal" USING btree
    ("Id_AnimalType" ASC NULLS LAST)
    TABLESPACE pg_default;


--INSERT DATA TEST
INSERT INTO public."AnimalType"("Code", "Name")
VALUES('LN', 'León');
INSERT INTO public."AnimalType"("Code", "Name")
VALUES('TG', 'Tigre');
INSERT INTO public."AnimalType"("Code", "Name")
VALUES('ELF', 'Elefante'); 
INSERT INTO public."AnimalType"("Code", "Name")
VALUES('GR', 'Gorila'); 