-- Table: public."AspNetUsers"
-- DROP TABLE public."AspNetUsers";

CREATE TABLE public."AspNetUsers"
(
    "Id" uuid NOT NULL,
    "UserName" character varying(256) COLLATE pg_catalog."default",
    "NormalizedUserName" character varying(256) COLLATE pg_catalog."default",
    "Email" character varying(256) COLLATE pg_catalog."default",
    "NormalizedEmail" character varying(256) COLLATE pg_catalog."default",
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default",
    "SecurityStamp" text COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    "PhoneNumber" text COLLATE pg_catalog."default",
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."AspNetUsers"
    OWNER to security_manager;
-- Index: EmailIndex
-- DROP INDEX public."EmailIndex";

CREATE INDEX "EmailIndex"
    ON public."AspNetUsers" USING btree
    ("NormalizedEmail" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: UserNameIndex
-- DROP INDEX public."UserNameIndex";

CREATE UNIQUE INDEX "UserNameIndex"
    ON public."AspNetUsers" USING btree
    ("NormalizedUserName" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public."AspNetRoles"
-- DROP TABLE public."AspNetRoles";

CREATE TABLE public."AspNetRoles"
(
    "Id" uuid NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default",
    "NormalizedName" character varying(256) COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."AspNetRoles"
    OWNER to security_manager;
-- Index: RoleNameIndex
-- DROP INDEX public."RoleNameIndex";

CREATE UNIQUE INDEX "RoleNameIndex"
    ON public."AspNetRoles" USING btree
    ("NormalizedName" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public."AspNetUserRoles"
-- DROP TABLE public."AspNetUserRoles";

CREATE TABLE public."AspNetUserRoles"
(
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    "Discriminator" text COLLATE pg_catalog."default" NOT NULL,
    "UserId1" uuid,
    "RoleId1" uuid,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES public."AspNetRoles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId1" FOREIGN KEY ("RoleId1")
        REFERENCES public."AspNetRoles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId1" FOREIGN KEY ("UserId1")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE public."AspNetUserRoles"
    OWNER to security_manager;
-- Index: IX_AspNetUserRoles_RoleId
-- DROP INDEX public."IX_AspNetUserRoles_RoleId";

CREATE INDEX "IX_AspNetUserRoles_RoleId"
    ON public."AspNetUserRoles" USING btree
    ("RoleId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_AspNetUserRoles_RoleId1
-- DROP INDEX public."IX_AspNetUserRoles_RoleId1";

CREATE INDEX "IX_AspNetUserRoles_RoleId1"
    ON public."AspNetUserRoles" USING btree
    ("RoleId1" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_AspNetUserRoles_UserId1
-- DROP INDEX public."IX_AspNetUserRoles_UserId1";

CREATE INDEX "IX_AspNetUserRoles_UserId1"
    ON public."AspNetUserRoles" USING btree
    ("UserId1" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public."AspNetRoleClaims"
-- DROP TABLE public."AspNetRoleClaims";

CREATE TABLE public."AspNetRoleClaims"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "RoleId" uuid NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES public."AspNetRoles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."AspNetRoleClaims"
    OWNER to security_manager;
-- Index: IX_AspNetRoleClaims_RoleId
-- DROP INDEX public."IX_AspNetRoleClaims_RoleId";

CREATE INDEX "IX_AspNetRoleClaims_RoleId"
    ON public."AspNetRoleClaims" USING btree
    ("RoleId" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public."AspNetUserClaims"
-- DROP TABLE public."AspNetUserClaims";

CREATE TABLE public."AspNetUserClaims"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" uuid NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."AspNetUserClaims"
    OWNER to security_manager;
-- Index: IX_AspNetUserClaims_UserId
-- DROP INDEX public."IX_AspNetUserClaims_UserId";

CREATE INDEX "IX_AspNetUserClaims_UserId"
    ON public."AspNetUserClaims" USING btree
    ("UserId" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public."AspNetUserLogins"
-- DROP TABLE public."AspNetUserLogins";

CREATE TABLE public."AspNetUserLogins"
(
    "LoginProvider" text COLLATE pg_catalog."default" NOT NULL,
    "ProviderKey" text COLLATE pg_catalog."default" NOT NULL,
    "ProviderDisplayName" text COLLATE pg_catalog."default",
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."AspNetUserLogins"
    OWNER to security_manager;
-- Index: IX_AspNetUserLogins_UserId
-- DROP INDEX public."IX_AspNetUserLogins_UserId";

CREATE INDEX "IX_AspNetUserLogins_UserId"
    ON public."AspNetUserLogins" USING btree
    ("UserId" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public."AspNetUserTokens"
-- DROP TABLE public."AspNetUserTokens";
CREATE TABLE public."AspNetUserTokens"
(
    "UserId" uuid NOT NULL,
    "LoginProvider" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Value" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."AspNetUserTokens"
    OWNER to security_manager;


--INSERT DATA TEST
INSERT INTO public."AspNetRoles"("Id", "Name", "NormalizedName", "ConcurrencyStamp")
VALUES('4aa12b28-f958-4128-a578-b4a316f35937', 'Administrador', 'ADMINISTRADOR', 'E3CQR4AEZMMCB5EIBJGLUCDGVF6O3PNS');

INSERT INTO public."AspNetRoles"("Id", "Name", "NormalizedName", "ConcurrencyStamp")
VALUES('5afa1cf7-dd31-4ead-8373-2f710487a1c5', 'Funcionario', 'FUNCIONARIO', 'E3CQR4AEZMMCB5EIBJGLUCDGVF6O3SNP');

INSERT INTO public."AspNetUsers"("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount")
VALUES ('fcc2d156-6e4f-441e-9213-0ed54305a5b5', 'vecheverria', 'VECHEVERRIA', 'viktoralfa19@hotmail.com',
'VIKTORALFA19@HOTMAIL.COM', true,
'AQAAAAEAACcQAAAAEK0P3wqVX+wVwCkh+IGz75osuM+O/Ze3pzy6kWH4tzJOYT5d9YEUvd4cJaSjlB8Ykw==',
'E3CQR4AEZMMCB5EIBJGLUCDGVF6O3PNS', 'a5c8b60a-ef7c-4400-922f-623e226e1431',
'0995005863', false, false, null, true, 0);

INSERT INTO public."AspNetUsers"("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount")
VALUES ('c550c465-0bb7-408a-af91-9a9e7a1d9cbf', 'babarca', 'BABARCA', 'viktoralfa19@gmail.com',
'VIKTORALFA19@GMAIL.COM', true,
'AQAAAAEAACcQAAAAEK0P3wqVX+wVwCkh+IGz75osuM+O/Ze3pzy6kWH4tzJOYT5d9YEUvd4cJaSjlB8Ykw==',
'E3CQR4AEZMMCB5EIBJGLUCDGVF6O3PNS', 'a5c8b60a-ef7c-4400-922f-623e226e1431',
'0995005863', false, false, null, true, 0);

INSERT INTO public."AspNetUserRoles"("UserId", "RoleId", "Discriminator")
VALUES('fcc2d156-6e4f-441e-9213-0ed54305a5b5', '4aa12b28-f958-4128-a578-b4a316f35937', 'ApplicationUserRole');

INSERT INTO public."AspNetUserRoles"("UserId", "RoleId", "Discriminator")
VALUES('c550c465-0bb7-408a-af91-9a9e7a1d9cbf', '5afa1cf7-dd31-4ead-8373-2f710487a1c5', 'ApplicationUserRole');